Repository googleapis/java-analytics-admin, pull requests merged in 2020-08, with the labels that each got.

#20 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#22 samples: add quickstart sample app
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/analyticsadmin/QuickstartSample.java
  samples/snippets/src/test/java/com/example/analyticsadmin/QuickstartSampleTest.java
Labels: cla: yes

#28 chore: regenerate README versions
  README.md
  samples/install-without-bom/pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: none

#30 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#31 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#32 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
