Repository googleapis/java-analytics-admin, pull requests merged in 2021-03, with the labels that each got.

#179 fix: add `https://www.googleapis.com/auth/analytics.edit` OAuth2 scope to the list of acceptable scopes for all read only methods
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.java
  grpc-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceGrpc.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAccountRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAccountRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAndroidAppDataStreamRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAndroidAppDataStreamRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateEnhancedMeasurementSettingsRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateEnhancedMeasurementSettingsRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateFirebaseLinkRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateFirebaseLinkRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateGoogleAdsLinkRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateGoogleAdsLinkRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateIosAppDataStreamRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateIosAppDataStreamRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdatePropertyRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdatePropertyRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateWebDataStreamRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateWebDataStreamRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/proto/google/analytics/admin/v1alpha/analytics_admin.proto
  proto-google-analytics-admin-v1alpha/src/main/proto/google/analytics/admin/v1alpha/resources.proto
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#181 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: analyticsadmin, automerge, cla: yes

#182 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#183 chore(release): update Java microgenerator to 1.0.1
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceSettings.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/package-info.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/AnalyticsAdminServiceStub.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/AnalyticsAdminServiceStubSettings.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/GrpcAnalyticsAdminServiceCallableFactory.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/GrpcAnalyticsAdminServiceStub.java
  google-analytics-admin/src/test/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClientTest.java
  google-analytics-admin/src/test/java/com/google/analytics/admin/v1alpha/MockAnalyticsAdminService.java
  google-analytics-admin/src/test/java/com/google/analytics/admin/v1alpha/MockAnalyticsAdminServiceImpl.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AccountName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AccountSummaryName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AndroidAppDataStreamName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/DataSharingSettingsName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/EnhancedMeasurementSettingsName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/FirebaseLinkName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/GlobalSiteTagName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/GoogleAdsLinkName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/IosAppDataStreamName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/PropertyName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UserLinkName.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/WebDataStreamName.java
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#184 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#185 chore: update gax-java dependency to 1.62
  grpc-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceGrpc.java
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#187 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#188 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.java
  google-analytics-admin/src/test/java/com/google/analytics/admin/v1alpha/MockAnalyticsAdminServiceImpl.java
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full, samples

#189 chore: add analytics-dpe as codeowner
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
  .repo-metadata.json
Labels: api: analyticsadmin, automerge, cla: yes

#190 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: analyticsadmin, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#191 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full
