Repository googleapis/java-analytics-admin, pull requests merged in 2021-01, with the labels that each got.

#132 chore: put markdown table in a codeblock
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ListPropertiesRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ListPropertiesRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/proto/google/analytics/admin/v1alpha/analytics_admin.proto
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: full

#134 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: analyticsadmin, automerge, cla: yes

#135 chore: update gapic-generator-java to 0.0.18
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceSettings.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/AnalyticsAdminServiceStub.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/GrpcAnalyticsAdminServiceCallableFactory.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/GrpcAnalyticsAdminServiceStub.java
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#137 fix!: remove unused fields from `EnhancedMeasurementSettings`
  .gitignore
  google-analytics-admin/clirr-ignored-differences.xml
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceSettings.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/AnalyticsAdminServiceStub.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/AnalyticsAdminServiceStubSettings.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/stub/GrpcAnalyticsAdminServiceStub.java
  google-analytics-admin/src/test/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClientTest.java
  grpc-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceGrpc.java
  proto-google-analytics-admin-v1alpha/clirr-ignored-differences.xml
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/Account.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AccountOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminProto.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/EnhancedMeasurementSettings.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/EnhancedMeasurementSettingsOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/FirebaseLink.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/FirebaseLinkOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/GlobalSiteTag.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/GlobalSiteTagOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/GoogleAdsLink.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/GoogleAdsLinkOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ListFirebaseLinksRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ListFirebaseLinksRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ListFirebaseLinksResponse.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ListFirebaseLinksResponseOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/Property.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/PropertyOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/ResourcesProto.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAccountRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAccountRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAndroidAppDataStreamRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateAndroidAppDataStreamRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateEnhancedMeasurementSettingsRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateEnhancedMeasurementSettingsRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateFirebaseLinkRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateFirebaseLinkRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateGoogleAdsLinkRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateGoogleAdsLinkRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateIosAppDataStreamRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateIosAppDataStreamRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdatePropertyRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdatePropertyRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateWebDataStreamRequest.java
  proto-google-analytics-admin-v1alpha/src/main/java/com/google/analytics/admin/v1alpha/UpdateWebDataStreamRequestOrBuilder.java
  proto-google-analytics-admin-v1alpha/src/main/proto/google/analytics/admin/v1alpha/analytics_admin.proto
  proto-google-analytics-admin-v1alpha/src/main/proto/google/analytics/admin/v1alpha/resources.proto
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#141 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: analyticsadmin, automerge, cla: yes

#144 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#145 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: analyticsadmin, automerge, cla: yes
