Repository googleapis/java-analytics-admin, pull requests merged in 2021-05, with the labels that each got.

#205 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: none

#206 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: analyticsadmin, automerge, cla: yes

#207 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#211 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#213 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .kokoro/release/publish_javadoc11.sh
  google-analytics-admin-bom/pom.xml
  google-analytics-admin/pom.xml
  owlbot.py
  pom.xml
  samples/snippets/src/main/java/com/example/analyticsadmin/QuickstartSample.java
  samples/snippets/src/test/java/com/example/analyticsadmin/QuickstartSampleTest.java
  versions.txt
Labels: api: analyticsadmin, automerge, cla: yes

#219 build: switch all clients to use the google endpoint on sonatype
  pom.xml
Labels: api: analyticsadmin, automerge, cla: yes
