Repository googleapis/java-analytics-admin, pull requests merged in 2021-02, with the labels that each got.

#149 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: analyticsadmin, cla: yes, context: partial

#150 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#151 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#153 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#152 docs: generate sample code in the Java microgenerator
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.java
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/package-info.java
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full, samples

#157 chore: switch to using pre-generated library
  synth.py
Labels: api: analyticsadmin, automerge, cla: yes

#158 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#170 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-analytics-admin/src/main/java/com/google/analytics/admin/v1alpha/gapic_metadata.json
  synth.metadata
Labels: api: analyticsadmin, automerge, cla: yes, context: full

#171 samples: rename countryCode to regionCode
  samples/snippets/src/main/java/com/example/analyticsadmin/QuickstartSample.java
Labels: api: analyticsadmin, automerge, cla: yes, samples

#177 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: analyticsadmin, automerge, cla: yes
